id: b52d934f-469b-4908-997f-fc097b17442b
Function:
  Title: Union Parser for all TransmitSecurity Events
  Version: '1.0.0'
  LastUpdated: Jun 6th 2024
Category: TransmitSecurityParser
FunctionName: TransmitSecurityEventParser
FunctionAlias: TransmitSecurityEventParser
FunctionParams:
  - Name: starttime
    Type: datetime
    Default: datetime(null)
  - Name: endtime
    Type: datetime
    Default: datetime(null)
  - Name: tablesRequired
    Type: dynamic
    Default: dynamic([])
  - Name: eventTypesRequired
    Type: dynamic
    Default: dynamic([])
FunctionQuery: |
  let parser = (
      starttime:datetime=datetime(null), 
      endtime:datetime=datetime(null), 
      tablesRequired:dynamic=dynamic([]), 
      eventTypesRequired:dynamic=dynamic([])
  )
  {
      union isfuzzy=true
      (
          TransmitSecurityUserActivity
          | where array_length(tablesRequired) == 0 or "UserActivity" in~ (tablesRequired)
          | where (isnull(starttime) or timestamp >= starttime)
                and (isnull(endtime) or timestamp <= endtime)
          | where array_length(eventTypesRequired) == 0 or activity in~ (eventTypesRequired)
      ),
      (
          TransmitSecurityAdminActivity
          | where array_length(tablesRequired) == 0 or "AdminActivity" in~ (tablesRequired)
          | where (isnull(starttime) or timestamp >= starttime)
                and (isnull(endtime) or timestamp <= endtime)
          | where array_length(eventTypesRequired) == 0 or activity in~ (eventTypesRequired)
      )
  };
  parser(
      starttime=starttime, 
      endtime=endtime, 
      tablesRequired=tablesRequired, 
      eventTypesRequired=eventTypesRequired
  )
