jobs:
- job: "KqlValidations"
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    GITHUB_APP_ID: $(GitHubAppID)
    GITHUB_INSTALLATION_ID: $(GitHubAppInstallationID)
    GITHUB_PRIVATE_KEY: $(GitHubAppPrivateKey)
    buildConfiguration: 'Release'
    dotnetSdkVersion: '6.0.x'
    PRNUM: $(System.PullRequest.PullRequestNumber)
  steps:
    - script: |
        echo "GitHub App ID: $(GITHUB_APP_ID)"
        echo "Installation ID: $(GITHUB_INSTALLATION_ID)"
        echo "Private Key: $(GITHUB_PRIVATE_KEY)"
        echo "Build Configuration: $(buildConfiguration)"
        echo "Dotnet SDK Version: $(dotnetSdkVersion)"
        echo "PR Number: $(PRNUM)"
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetSdkVersion)'
    - task: DotNetCoreCLI@2
      displayName: 'Run kql validation tests'
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'
        publishTestResults: true
        projects: '**/Kqlvalidations.Tests.csproj'
