jobs:
- job: "KqlValidations"
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    - group: Github_Validations  # Reference the variable group
  steps:
    - script: echo "##vso[task.setvariable variable=GitHubAppID;isOutput=true]$(GitHubAppID)"
    - script: echo "##vso[task.setvariable variable=GitHubAppInstallationID;isOutput=true]$(GitHubAppInstallationID)"
    - script: echo "##vso[task.setvariable variable=GitHubAppPrivateKey;isOutput=true]$(GitHubAppPrivateKey)"
    - script: echo "##vso[task.setvariable variable=PRNUM;isOutput=true]$(System.PullRequest.PullRequestNumber)"
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetSdkVersion)'
    - task: DotNetCoreCLI@2
      displayName: 'Run kql validation tests'
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'
        publishTestResults: true
        projects: '**/Kqlvalidations.Tests.csproj'
