jobs:
- job: "KqlValidations"
  pool:
    vmImage: 'ubuntu-latest'
  env:
    GITHUB_APP_PRIVATE_KEY: $(GitHubAppPrivateKey)
  variables:
    buildConfiguration: 'Release'
    dotnetSdkVersion: '6.0.x'
    PRNUM: $(System.PullRequest.PullRequestNumber)
  steps:
    - script: |
        echo "GitHub App ID from yaml: $(GitHubAppID)"
        echo "Installation ID: $(GitHubAppInstallationID)"
        echo "Private Key: $GITHUB_APP_PRIVATE_KEY"  # Using environment variable syntax in the script
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetSdkVersion)'
    - task: DotNetCoreCLI@2
      displayName: 'Run kql validation tests'
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'
        publishTestResults: true
        projects: '**/Kqlvalidations.Tests.csproj'
