jobs:
- job: "KqlValidations"
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    buildConfiguration: 'Release'
    dotnetSdkVersion: '6.0.x'
    PRNUM: $(System.PullRequest.PullRequestNumber)
    GITHUBAPPID111: $(GitHubAppID)
    GITHUBAPPINSTALLATIONID111: $(GitHubAppInstallationID)
    GITHUBAPPPRIVATEKEY111: $(GitHubAppPrivateKey)
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetSdkVersion)'
    - task: DotNetCoreCLI@2
      displayName: 'Run kql validation tests'
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'
        publishTestResults: true
        projects: '**/Kqlvalidations.Tests.csproj'