jobs:
- job: "KqlValidations"
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    GitHubAppID: $(GitHubAppID)
    GitHubAppInstallationID: $(GitHubAppInstallationID)
    GitHubAppPrivateKey: $(GitHubAppPrivateKey)
    buildConfiguration: 'Release'
    dotnetSdkVersion: '6.0.x'
    PRNUM: $(System.PullRequest.PullRequestNumber)
  steps:
    - script: |
        echo "GitHub App ID from yaml: $(GitHubAppID)"
        echo "Installation ID from yaml: $(GitHubAppInstallationID)"
        echo "Private Key from yaml: $(GitHubAppPrivateKey)"
        echo "Build Configuration: $(buildConfiguration)"
        echo "Dotnet SDK Version: $(dotnetSdkVersion)"
        echo "PR Number: $(PRNUM)"
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetSdkVersion)'
    - task: DotNetCoreCLI@2
      displayName: 'Run kql validation tests'
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'
        publishTestResults: true
        projects: '**/Kqlvalidations.Tests.csproj'
