jobs:
- job: "KqlValidations"
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    buildConfiguration: 'Release'
    dotnetSdkVersion: '6.0.x'
    FOO: $(GitHubAppPrivateKey)
  steps:
    - bash: |
        echo "$FOO"
        echo "$NITIN"
      env:
        FOO: $(FOO)
        NITIN: $(System.PullRequest.PullRequestNumber) 
    - pwsh: |
        Write-Host "$($env:SAMPLE)"
      env:
        SAMPLE: $(GitHubAppPrivateKey)  
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetSdkVersion)'
    - task: DotNetCoreCLI@2
      displayName: 'Run kql validation tests'
      env:
        AMOL: $(GitHubAppPrivateKey)
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'
        publishTestResults: true
        projects: '**/Kqlvalidations.Tests.csproj'

