jobs:
- job: "KqlValidations"
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    buildConfiguration: 'Release'
    dotnetSdkVersion: '6.0.x'
    PRNUM: $(System.PullRequest.PullRequestNumber)
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetSdkVersion)'
    - task: AzureKeyVault@2
      inputs:
        azureSubscriptionEndpoint: 'eco-connector-test-service-connection'
        KeyVaultName: 'keyvaultforcatgithub'
        SecretsFilter: '*'
    - script: |
        # Print fetched secrets
        echo "GITHUBAPPID: $(GITHUBAPPID)"
        echo "GITHUBAPPINSTALLATIONID: $(GITHUBAPPINSTALLATIONID)"
        echo "GITHUBAPPPRIVATEKEY: $(GITHUBAPPPRIVATEKEY)"

        # Set environment variables using the values fetched from Azure Key Vault
        export GITHUBAPPID=$(GITHUBAPPID)
        export GITHUBAPPINSTALLATIONID=$(GITHUBAPPINSTALLATIONID)
        export GITHUBAPPPRIVATEKEY=$(GITHUBAPPPRIVATEKEY)
      displayName: 'Print and Set Environment Variables'
    - task: DotNetCoreCLI@2
      displayName: 'Run kql validation tests'
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'
        publishTestResults: true
        projects: '**/Kqlvalidations.Tests.csproj'
