name: Check if Automated Pull Request

on:
  workflow_call:
    outputs:
      isAutomatedPR:
        description: "Is Automated PR"
        value: ${{ jobs.checkAutomatedPR.outputs.isAutomatedPR }}

permissions:
  contents: read
  pull-requests: read

env:
  BRANCH_NAME: ${{ github.event.client_payload.pull_request.head.ref || github.event.client_payload.pullRequestBranchName }}
  BODY: ${{ github.event.issue.body }}

jobs:
  checkAutomatedPR:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    outputs:
      isAutomatedPR: ${{ steps.ValidateAutomatedPR.outputs.isAutomatedPR }}
    steps:
      - shell: pwsh
        id: ValidateAutomatedPR
        run: |
          $pullRequestBranchName = "$env:BranchName"
          Write-Host "Pull Request Branch Name is $pullRequestBranchName"
          $isAutomatedPR = $false
          if ($pullRequestBranchName -like '*automated-pr')
          {
            Write-Host "Skipping packaging as it is an automated pr!"
            $isAutomatedPR = $true
          }
          Write-Output "isAutomatedPR=$isAutomatedPR" >> $env:GITHUB_OUTPUT
          Write-Host "Is this Pull Request autogenerated $isAutomatedPR"
