name: Validate Hyperlinks in PR
env:
  BASE_FOLDER_PATH: "${{ vars.BASEFOLDERPATH }}"
  APPINSIGHTS: "${{ vars.APPINSIGHTS }}"
on:
  pull_request:
    branches:
      - master
    paths:
      - Solutions/**

jobs:
  validate-pr-links:
    if: ${{ !github.event.pull_request.head.repo.fork && !contains(github.event.client_payload.pull_request.head.ref , 'dependabot/') && !contains(github.event.client_payload.pullRequestBranchName , 'dependabot/') }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - shell: pwsh
        id: step1
        name: Identify Changes in PR
        env:
          RUNID: "${{ github.run_id }}"
          PULL_REQUEST_NUMBER: "${{ github.event.client_payload.pull_request.number || github.event.client_payload.pullRequestNumber || github.event.pull_request.number }}"
        run: |
          $runId = "${{ env.RUNID }}"
          $instrumentationKey = "${{ env.APPINSIGHTS }}"
          $pullRequestNumber = "${{ env.PULL_REQUEST_NUMBER }}"
          $baseFolderPath = "${{ env.BASE_FOLDER_PATH }}" 
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module powershell-yaml
          ./.script/package-automation/hyperlink-validation.ps1 $runId $pullRequestNumber $instrumentationKey $baseFolderPath