name: Detection Validations
run-name: Detection Validations running on ${{ github.ref_name }}
on:
    pull_request:
        branches:
            - master
    # Allows to run workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    KqlValidations:
      runs-on: ubuntu-latest
      env:
        buildConfiguration: Release
        dotnetSdkVersion: 6.0.x
        PRNUM: ${{ github.event.pull_request.number }}
      steps:
      - uses: actions/checkout@v4
      - name: Use .NET Core SDK ${{ env.dotnetSdkVersion }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnetSdkVersion }}
      - name: Run kql validation tests
        run: dotnet test .script/tests/KqlvalidationsTests/Kqlvalidations.Tests.csproj --configuration ${{ env.buildConfiguration }}
        env:
          GITHUBAPPID: ${{ env.GitHubAppID }}
          GITHUBAPPINSTALLATIONID: ${{ env.GitHubAppInstallationID }}
          GITHUBAPPPRIVATEKEY: ${{ env.GitHubAppPrivateKey }}
                      